
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const DMCA = lazy(() => import("./pages/DMCA.tsx"));
const FAQ = lazy(() => import("./pages/FAQ.tsx"));
const Features = lazy(() => import("./pages/Features.tsx"));
const Pricing = lazy(() => import("./pages/Pricing.tsx"));
const PrivacyPolicy = lazy(() => import("./pages/PrivacyPolicy.tsx"));
const RefundPolicy = lazy(() => import("./pages/RefundPolicy.tsx"));
const Robots = lazy(() => import("./pages/Robots.tsx"));
const SetupGuides = lazy(() => import("./pages/SetupGuides.tsx"));
const Sitemap = lazy(() => import("./pages/Sitemap.tsx"));
const TermsOfService = lazy(() => import("./pages/TermsOfService.tsx"));
const Testimonials = lazy(() => import("./pages/Testimonials.tsx"));
const UsingAI = lazy(() => import("./pages/UsingAI.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/contact", element: <Contact />},
	{ path: "/dmca", element: <DMCA />},
	{ path: "/faq", element: <FAQ />},
	{ path: "/features", element: <Features />},
	{ path: "/pricing", element: <Pricing />},
	{ path: "/privacy-policy", element: <PrivacyPolicy />},
	{ path: "/privacypolicy", element: <PrivacyPolicy />},
	{ path: "/refund-policy", element: <RefundPolicy />},
	{ path: "/refundpolicy", element: <RefundPolicy />},
	{ path: "/robots", element: <Robots />},
	{ path: "/setup-guides", element: <SetupGuides />},
	{ path: "/setupguides", element: <SetupGuides />},
	{ path: "/sitemap", element: <Sitemap />},
	{ path: "/terms-of-service", element: <TermsOfService />},
	{ path: "/termsofservice", element: <TermsOfService />},
	{ path: "/testimonials", element: <Testimonials />},
	{ path: "/using-ai", element: <UsingAI />},
	{ path: "/usingai", element: <UsingAI />},

];
